apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluent-bit-pvc
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi  # Adjust the storage capacity as needed