apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: music-albums-app

resources:
- namespace.yml
- db-secret.yml
- server-deployment.yml
- server-service.yml
- redis-service.yml
- redis-statefulset.yml
- tls-secret.yml
- ingress.yml